id: P007945
initial_creation_type: ocr
source_metadata:
  id: bdr:W3CN7648
  title: དཔལ་གསང་བ་འདུས་པ་ཞེས་བྱ་བའི་རྒྱུད་ཀྱི་རྒྱལ་པོ་ཆེན་པོ།
  author: ''
  volumes:
    dfae73c717c84deeb99b5554eaf46e17:
      image_group_id: I3CN7650
      title: ''
      volume_number: 1
      total_pages: 146
ebook_metadata:
  title: དཔལ་གསང་བ་འདུས་པ་ཞེས་བྱ་བའི་རྒྱུད་ཀྱི་རྒྱལ་པོ་ཆེན་པོ།
  author: ''
  sku: P007945
  cover: cover.jpg
  layers:
  - pagination
