id: P007945
initial_creation_type: ocr
created_at: 22/03/2020
last_modified_at: 25/11/2021
source_metadata:
  id: bdr:W3CN7648
  title: དཔལ་གསང་བ་འདུས་པ་ཞེས་བྱ་བའི་རྒྱུད་ཀྱི་རྒྱལ་པོ་ཆེན་པོ།
  author: ''
  volumes:
    4371578d23c4430e9b4b1f1f25fd304e:
      image_group_id: I3CN7650
      title: Volume 1 of dpal gsang ba 'dus pa zhes bya ba'i rgyud kyi rgyal po chen
        po/
      volume_number: 1
      total_pages: 146
      base_file: v001.txt
