id: I003EB043
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-22T21:23:13+00:00'
last_modified: '2022-06-09T07:50:26.530981+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W3CN7648
  title: དཔལ་གསང་བ་འདུས་པ་ཞེས་བྱ་བའི་རྒྱུད་ཀྱི་རྒྱལ་པོ་ཆེན་པོ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    2E39:
      image_group_id: I3CN7650
      title: Volume 1 of dpal gsang ba 'dus pa zhes bya ba'i rgyud kyi rgyal po chen
        po/
      total_pages: 146
      order: 1
      base_file: 2E39.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
